version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '27081:9000'
    container_name: wxcloud_wx_youth_point
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=wx_youth_point
      - role=container
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=9qQZDBrZ
      - MYSQL_ADDRESS=10.32.108.126:3306
      - COS_BUCKET=7072-prod-4gjlstdw9f5f0d7d-1318978931
      - COS_REGION=ap-shanghai
      - DATA_BASE=youth_point
      - APP_ID=wx4f2dbbae1029571a
      - APP_SECRET=8f5de26f06c3c42e5eec051738b422b9
networks:
  default:
    external:
      name: wxcb0
